const members = {
    'postdoc': [
        // {
        //     name: '楊謦瑜',
        //     alias: 'Helen',
        //     research: '#',
        //     img: 'img/helen.jpg',
        //     color: 'red',
        //     intro: '我要減肥',
        //     link: '#',
        // },
        // {
        //     name: '杜海倫',
        //     alias: 'Helen',
        //     research: '#',
        //     img: 'img/helentu.jpg',
        //     color: 'orange',
        //     intro: '海倫仙度絲去屑洗髮乳',
        //     link: '#',
        // },
    ],
    'phd-students': [
        // {
        //     name: 'Joanne Boisson',
        //     alias: '喬安娜',
        //     research: '#',
        //     img: 'img/joanne.jpg',
        //     color: 'red',
        //     intro: '#',
        //     link: '#',
        // },
        {
            name: '陳志杰',
            alias: 'jjc',
            research: 'Machine Translation',
            img: 'img/jjc.jpg',
            color: 'black',
            intro: '我是胖虎我是孩子王',
            link: 'https://dspp779.github.io',
        },
        {
            name: '段凱文',
            alias: 'Kevin',
            research: '#',
            img: 'img/kevin.jpg',
            color: 'olive',
            intro: '斷水流大師兄',
            link: '',
        },
    ],
    'ra': [
        // {
        //     name: '彭晧鈞',
        //     alias: 'Henry',
        //     research: '',
        //     img: 'img/henry.jpg',
        //     color: 'blue',
        //     intro: '',
        //     link: '',
        // },
        // {
        //     name: '羅曼',
        //     alias: 'Frances',
        //     research: '',
        //     img: 'img/frances.jpg',
        //     color: 'blue',
        //     intro: '我顛倒了整個世界，只為擺正你的倒影',
        //     link: 'https://www.youtube.com/watch?v=pykyNOEVqCU',
        // },
        // {
        //     name: '蓋嘉瑋',
        //     alias: 'Jess',
        //     research: '',
        //     img: 'img/jess.jpg',
        //     color: 'blue',
        //     intro: '只要游泳',
        //     link: '',
        // },
        // {
        //     name: '陳怡蓓',
        //     alias: 'Erin',
        //     research: '',
        //     img: 'img/yipei.jpg',
        //     color: 'grey    ',
        //     intro: '買東西？上ebay！',
        //     link: '',
        //  },
        //  {
        //     name: '蔡名喬',
        //     alias: 'Mictsai',
        //     research: '#',
        //     img: 'img/Mictsai.jpg',
        //     color: 'red',
        //     intro: '宅錯了嗎',
        //     link: 'https://www.youtube.com/watch?v=PBplpprOdyw',
        //  },
        // {
        //     name: '林依蒨',
        //     alias: 'Nica',
        //     research: '碩班找教授面談請寄信給我',
        //     img: 'img/nica.jpg',
        //     color: 'blue',
        //     intro: 'Hi',
        //     link: 'https://nicalin.github.io',
        // },
        {
            name: '劉千瑜',
            alias: 'Celeste',
            research: '#',
            img: 'img/celeste.jpeg',
            color: 'green',
            intro: '欲預約老師會談時間可來信聯絡',
            link: 'mailto:cianyul@nlplab.cc',
        },
    ],
    'ms-students': [
        {
            name: '劉宗翰',
            alias: 'Hank',
            research: '#',
            img: 'img/hank.jpg',
            color: '#0072B5',
            intro: '打球啊',
            link: '',
        },
        {
            name: 'Silvia Gabriela Herrera Poggio',
            alias: 'Gaby',
            research: 'Automatic Essay Scoring ',
            img: 'img/gaby.jpg',
            color: '#F5DF4D',
            intro: "Hello there! I'm an international master's student from Guatemala, with a background in systems and informatics engineering, as well as full-stack web development. I'm also an energetic and friendly person who absolutely adores dogs!",
            link: 'https://www.linkedin.com/in/gabriela-herrera-poggio',
        },        
        {
            name: '李瑋芹',
            alias: 'Kelly',
            research: '#',
            img: 'img/kelly.jpg',
            color: '#B55A30',
            intro: '(´･_･`)',
            link: '',
        },
        {
            name: '謝瑞峰',
            alias: 'Andy',
            research: '#',
            img: 'img/andy.jpg',
            color: '#FDAC53',
            intro: 'Hi~',
            link: '',
        },
        {
            name: '張方瑜',
            alias: 'Rola',
            research: '#',
            img: 'img/rola.jpg',
            color: '#9BB7D4',
            intro: 'こんにちは～',
            link: '',
        },
        {
            name: '朱育欣',
            alias: 'winnie',
            research: '#',
            img: 'img/winnie111.jpg',
            color: '#E9897E',
            intro: '###',
            link: '',
        },
        {  
            name: '江詠筑',
            alias: 'Angie',
            research: 'generative WSD',
            img: 'img/chuchu.jpg',
            color: '#88B04B',
            intro: '我是誰 我怎麼在這裡',
            link: 'https://imyungchu.github.io/',
        },
        {
            name: '林子謙',
            alias: 'Chien',
            research: '#',
            img: 'img/chien.jpg',
            color: '#6B5B95',
            intro: 'Para la vida que quiero, no hay atajos.',
            link: '',
        },
        {
            name: '黃苡溱',
            alias: 'Emma',
            research: '#',
            img: 'img/emma.jpg',
            color: '#FF6F61',
            intro: 'Guten Tag!',
            link: '',
        },
        {
            name: '許承恩',
            alias: 'Irene',
            research: '#',
            img: 'img/irene123.jpg',
            color: '#F7CAC9',
            intro: '嗨咿！',
            link: '',
        },
        {
            name: '蕭宇辰',
            alias: 'ChenChen',
            research: '#',
            img: 'img/chenchen.jpg',
            color: '#92A8D1',
            intro: '清大辰辰',
            link: '',
        },
        {
            name: '張兆慶',
            alias: 'Roger',
            research: '#',
            img: 'img/roger.jpg',
            color: '#34568B',
            intro: 'Life is what happens when you are busy making other plans.',
            link: '',
        },
        {
            name: 'Angelica Cassandra Loria',
            alias: 'AC',
            research: 'CEFR automated scoring using transition words',
            img: 'img/ac.jpg',
            color: 'black',
            intro: "I am AC and I like riding a bike to go to Nanliao.",
            link: 'WhatsApp: +886937651322',
        }
    ],
    'undergraduates': [
        // {
        //     name: '徐芷翎',
        //     alias: 'Amy',
        //     research: 'Email寫作輔助',
        //     img: 'img/amy.jpg',
        //     color: 'orange',
        //     intro: '',
        //     link: '',
        // },
        // {
        //     name: '簡紹安',
        //     alias: 'Shao-An',
        //     research: '自然語言搜尋介面',
        //     img: 'img/shaoan.jpg',
        //     color: 'yellow',
        //     intro: '',
        //     link: '',
        // },
        // {
        //     name: '蔡明勳',
        //     alias: 'Frank',
        //     research: '自然語言搜尋介面',
        //     img: 'img/frank.jpg',
        //     color: 'green',
        //     intro: '',
        //     link: '',
        // },
        //{
        //    name: '沈冠妤',
        //    alias: 'Sunny',
        //    research: '#',
        //    img: 'img/sunny.jpg',
        //    color: 'orange',
        //    intro: '快畢業了！應該吧！',
        //    link: '',
        //},
        //{
        //    name: '謝岑',
        //    alias: 'Sandy',
        //    research: '#',
        //    img: 'img/sandy.jpg',
        //    color: 'blue',
        //    intro: '花蓮仔騎山豬！',
        //    link: 'https://youtu.be/QbhmTM1cRro',
        //},
        //{
        //    name: '林欣葶',
        //    alias: 'Astrid',
        //    research: '#',
        //    img: 'img/astrid.jpg',
        //    color: 'green',
        //    intro: '提壁、岩壁，どっち？',
        //    link: '',
        //}
    ],
    'partners': [
        {
            name: '楊謦瑜',
            alias: 'Helen',
            research: '國立中興大學外語系',
            img: 'img/helen.jpg',
            color: 'red',
            intro: '我要減肥',
            link: '#',
        },
        {
            name: '杜海倫',
            alias: 'Helen',
            research: '輔仁大學圖資系',
            img: 'img/helentu.jpg',
            color: 'orange',
            intro: '海倫仙度絲去屑洗髮乳',
            link: '#',
        },
    ],
    'alumni': [
        {
            name: '葉玫慈',
            alias: 'Mei-Cih',
            research: 'Automatic Paraphrases Generation',
            img: 'img/meichi.jpg',
            color: 'red',
            intro: 'Ukulele是人生的一半(\'A`)',
            link: 'https://youtu.be/z2Xsp0HMqf8',
        },
        {
            name: '陳怡君',
            alias: 'Yi-Chun',
            research: '機器翻譯、同步樣式文法',
            img: 'img/chun.jpg',
            color: 'red',
            intro: '半夜睡不著覺，把心情哼成歌',
            link: 'https://youtu.be/O9cvAQEzG0o',
        },
        {
            name: '陳鵬宇',
            alias: 'Peng-Yu',
            research: '文法改錯',
            img: 'img/pengyu.jpg',
            color: 'yellow',
            intro: '太極拳法掌門人',
            link: 'https://youtu.be/wr-6wwt8RXk',
        },
        {
            name: '黃婕雅',
            alias: 'jr',
            research: 'Automatic Paraphrases Generation',
            img: 'img/jr.jpg',
            color: 'green',
            intro: '只是你遲到一千年！',
            link: 'https://youtu.be/83TjxZWFXVI',
        },
        {
            name: '吳奇恩',
            alias: 'Tony',
            research: '機器翻譯',
            img: 'img/57n.jpg',
            color: 'teal',
            intro: '57n',
            link: 'https://youtu.be/hgGFe4eJ0qc',
        },
        {
            name: '杜惟真',
            alias: 'Jane',
            research: '英語檢定輔助系統、動詞型態改錯',
            img: 'img/jane.jpg',
            color: 'blue',
            intro: '呵呵呵 好哦',
            link: 'https://youtu.be/7sbKm-hAlsw',
        },
        {
            name: '吳瑀瑄',
            alias: 'shanny',
            research: '自動文法改錯',
            img: 'img/shanny.jpg',
            color: 'violet',
            intro: '走啊，跑步！',
            link: 'https://youtu.be/m99Py_8NtZE',
        },
        {
            name: '羅右鈞',
            alias: 'Howard Lo',
            research: 'Deep Learning for NLP <3',
            img: 'img/howard.jpeg',
            color: 'brown',
            intro: '',
            link: 'https://www.youtube.com/watch?v=pbLJxFBOs80'
        },
        {
            name: '李巧雯',
            alias: 'ChiaoWen',
            research: 'Chinese Spelling Check',
            img: 'img/chiaowen.jpg',
            color: 'pink',
            intro: '',
            link: 'https://www.youtube.com/watch?v=e2QKlmMT8II',
        },
        {
            name: '林昌毅',
            alias: 'Chungyilin',
            research: '5 4 tusi be ba',
            img: 'img/chungyilin.jpg',
            color: 'grey',
            intro: '故人西辭黃鶴樓，煙花三月下揚州<br />孤帆遠影碧空盡，唯見長江天際流。',
            link: 'https://www.youtube.com/watch?v=HSHOU1OVbaY',
        },
        {
            name: '程尚謙',
            alias: 'Ashley',
            research: 'Word Sense Disambiguation',
            img: 'img/ashley.jpg',
            color: 'olive',
            intro: '',
            link: '#',
        },
        {
            name: '朱凰華',
            alias: 'Garnix',
            research: '#',
            img: 'img/garnix.jpg',
            color: 'red',
            intro: '無敵艦隊碾壓世界',
            link: 'https://www.youtube.com/watch?v=fTYgpGdvFa4',
        },
        {
            name: '蔡仲庭',
            alias: 'Ting',
            research: '#',
            img: 'img/ting.jpg',
            color: 'red',
            intro: '在看我嗎？',
            link: 'https://www.facebook.com/%E5%A6%99%E8%8A%B3%E5%A4%A7%E5%B8%AB-134564827164423/?ref=br_rs',
        },
        {
            name: '謝毅霖',
            alias: 'Charles',
            research: '#',
            img: 'img/yee0.jpg',
            color: 'yellow',
            intro: '矮額 偷看我喔',
            link: 'https://as10896.github.io',
        },
        {
            name: '彭成全',
            alias: 'Zeno',
            research: '#',
            img: 'img/zeno.jpg',
            color: 'black',
            intro: '',
            link: 'https://www.youtube.com/watch?v=HAIDqt2aUek',
        },
        {
            name: '韓文彬',
            alias: 'Vincent',
            research: '#',
            img: 'img/vincent.jpg',
            color: 'red',
            intro: '#',
            link: 'https://hanvincent.cc',
        },
        {
            name: '何佳芳',
            alias: 'Seafood',
            research: '#',
            img: 'img/fun.jpg',
            color: 'red',
            intro: '我愛獨角獸查理',
            link: 'https://www.youtube.com/watch?v=cMOHAcjlIWs',
        },
        {
            name: '蔡名喬',
            alias: 'Mictsai',
            research: '#',
            img: 'img/Mictsai.jpg',
            color: 'red',
            intro: '宅錯了嗎',
            link: 'https://www.youtube.com/watch?v=PBplpprOdyw',
        },
        {
            name: '賴怡惠',
            alias: 'Irene',
            research: '#',
            img: 'img/irene.jpg',
            color: 'red',
            intro: '',
            link: '',
        },
        {
            name: '陳映竹',
            alias: 'Jocelyn',
            research: '#',
            img: 'img/jocelyn.jpg',
            color: 'orange',
            intro: '教練我想打球',
            link: '',
        },
        {
            name: '何沛臻',
            alias: 'Patina',
            research: '#',
            img: 'img/patina.jpg',
            color: 'yellow',
            intro: '大家好我是PAPAYA',
            link: '',
        },
        {
            name: '郭俊豪',
            alias: 'Isaac',
            research: 'Grammar Pattern, Front-end Web Developement',
            img: 'img/isaac.jpg',
            color: 'green',
            intro: '史帝夫和戴夫都使用eToro投資金融市場',
            link: 'https://isaackwok.github.io/',
        },
        {
            name: '郭芝瑜',
            alias: 'cykuo',
            research: '#',
            img: 'img/cykuo.jpg',
            color: 'teal',
            intro: '好餓',
        },
        {
            name: '吳易東',
            alias: 'Yizzy',
            research: 'Grammatical Error Correction',
            img: 'img/yizzy.jpg',
            color: 'blue',
            intro: '這個人跟彭于晏有幾分神似',
            link: 'https://wohchowshy.github.io/',
        },
        {
            name: '許瑋芩',
            alias: 'Winnie',
            research: '#',
            img: 'img/winnie.jpg',
            color: 'violet',
            intro: 'Fearless',
            link: '',
        },
        {
            name: '侯芙堤',
            alias: 'jamie',
            research: '#',
            img: 'img/fb.jpg',
            color: 'brown',
            intro: 'Whole Foods, Whole People, Whole Planet.',
            link: '',
        },
        {
            name: '紀冠名',
            alias: 'sappy',
            research: 'Reading Comprehension, Machine Translation',
            img: 'img/sappy.jpg',
            color: 'pink',
            intro: '古明地覺最可愛！！',
            link: 'https://blog.sappy.tw/',
        },
        {
            name: '戴佑全',
            alias: 'Jacky',
            research: '#',
            img: 'img/jackytai.jpg',
            color: 'purple',
            intro: '十萬青年十萬肝，GG輪班救台灣',
            link: '',
        },
        {
            name: '吳岱儒',
            alias: 'Stanley',
            research: '#',
            img: 'img/stanley.jpg',
            color: 'brown',
            intro: 'QQ',
            link: '',
        },
        {
            name: '黃麟凱',
            alias: 'Jeff',
            research: '#',
            img: 'img/jeff.jpg',
            color: 'orange',
            intro: '每天都是一種練習',
            link: '',
        },
        {
            name: '李冠霖',
            alias: 'Simon',
            research: 'WSD, Reading Comprehension',
            img: 'img/simon.jpg',
            color: 'grey',
            intro: '奇怪的成員增加了！',
            link: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
        },
        {
            name: '許靜媛',
            alias: 'Caty',
            research: '#',
            img: 'img/jy.jpg',
            color: 'blue',
            intro: '同意啦，哪次不同意',
            link: '',
        },
        {
            name: '程筱珺',
            alias: 'diane',
            research: '#',
            img: 'img/diane.JPG',
            color: 'blue',
            intro: 'ʕ•ᴥ•ʔ',
            link: '',
        },
        {
            name: '吳㛢慈',
            alias: 'joanna',
            research: '#',
            img: 'img/joanna.png',
            color: 'blue',
            intro: 'It\'s not a bug; it\'s a FEATURE.¯\\_(ツ)_/¯',
            link: '',
        },
        {
            name: '彭冠復',
            alias: 'Elmon',
            research: '#',
            img: 'img/edmond.jpg',
            color: 'green',
            intro: 'Elmo, Lemon, Elmon',
            link: '',
        },
        {
            name: '張宜榛',
            alias: 'yichen',
            research: '#',
            img: 'img/yichen.png',
            color: 'teal',
            intro: 'Hello 你好 こんにちは',
            link: 'https://yakachang.github.io/',
        },
        {
            name: '陳麗光',
            alias: 'likuang',
            research: '#',
            img: 'img/lkchen.jpg',
            color: 'green',
            intro: '^•ﻌ•^ฅ',
            link: '',
        },
    ]
};
